image: node:10

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm i gulp-cli -g
  - npm i sass -g
  - npm install
  - npm rebuild node-sass
  - npm run exportScssColors
  - gulp build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
    - master
